version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - npm install -g hexo-cli
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - hexo generate
      - cd public
      - aws s3 sync . s3://blog.bravokeyl.com
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - public/**/*
  discard-paths: no
